# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54c78121ccbc1f5f95fe8fc6b48944a095b9b2fc6bc1751dac0551ff923bc1f291037cd7c2d9ebf2199389550298a92bee2b6609a0430aa4dc1777d0eab44e33

test:
  secret_key_base: 947971ed6a10ea5e661a75ae6b21b513fdd9695e5a27bb5823967cc49d7706ae10254c0a9ce5414d18ac956ae49dedaef79333dca4636026d1aab74662eac692

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
